language: python

python:
  - "3.2_with_system_site_packages"
  - 3.3
  - 3.4

before_install:
  - sudo apt-get install -qq python3-numpy python3-scipy
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION pip scipy numpy pytest
  - source activate testenv

script:
    - PYTHONPATH="." py.test tests
