language: python
python:
  - "3.3"

# Allow the use of packages installed via apt-get
# inside the virtualenv
virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python3-numpy

# Run tests
script:
    - PYTHONPATH="." py.test tests
